configfile: "config/config.yaml"

DATA_DIR = config['data_dir']

rule all:
    input:
        expand("{DATA_DIR}/C.txt", DATA_DIR=DATA_DIR)
    output:
        'wc_D.txt'
    shell:
        "wc -w {input} > {output}"

