configfile: "config/config.yaml"

DATA_DIR = config['data_dir']

rule all:
    input:
        expand("{DATA_DIR}/sample.txt", DATA_DIR=DATA_DIR)

rule sample:
    output:
        expand("{DATA_DIR}/sample.txt", DATA_DIR=DATA_DIR)
    script:
        "scripts/sample.py"